python: can't open file 'parallel_prepocessing.py': [Errno 2] No such file or directory
/var/spool/sge_prod/dc1s0b1c/job_scripts/3097513: line 15: syntax error near unexpected token `('
/var/spool/sge_prod/dc1s0b1c/job_scripts/3097513: line 15: `python parallel_single_run.py --infile infile.txt --varline ( sed -n '$SGE_TASK_IDp' varfile.txt )'
